### ISSUE TITLE
WebSocket connection failed

### ISSUE THREAD

**Issue by vanboom** [phusion/passenger-ruby-websocket-demo#2]
When I try to test this demo app on an Apache/Passenger based server, I get this message...

WebSocket connection to 'ws://www.flyonlinetools.help/websocket' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1

I think this is related to a WebSocket issue that I am having with another deployed app.  Any help is greatly appreciated!

UPDATE:  This error happens when I run under Apache/mod_passenger  4.0.46. 
When I run the demo application in a standalone using `bundle exec passenger start`, the demo works perfectly.  

UPDATE:  Upgraded Passenger to 5.0.18, error is now `failed: Error during WebSocket handshake: 'Connection' header is missing`

Thanks for any help that you could provide!  This is my first time with WebSockets, so I am struggling to debug.

**Comment by FooBarWidget** [comment]
Yes, WebSockets aren't supported under Apache yet. I'll update the documentation accordingly to avoid confusion.
