### ISSUE TITLE
EventMachine based websocket implementations

### ISSUE THREAD

**Issue by supairish** [phusion/passenger-ruby-websocket-demo#3]
Hello!

Thanks for this example.

One question, some of the more popular websocket libraries like [Firehose](https://github.com/polleverywhere/firehose) and [Faye](http://faye.jcoglan.com/ruby.html) use EventMachine to handle the websocket requests.  Is it possible to use one of these EventMachine based websocket libraries with Passenger?

For example Firehose is basically just a Rack app that wraps EventMachine.  

https://github.com/polleverywhere/firehose/blob/master/lib/firehose/server/app.rb#L47

Does this mean one could mount that rack app within their Rails app and it would work with Passenger?  Or would you have to have Nginx point Passenger to that Rack app and have it run as a separate process?

Any tips for how Passenger and EventMachine play together and fit into one of these scenarios?

Cheers

**Comment by FooBarWidget** [comment]
I've never used Firehose but Faye has explicit documentation on how to run on Passenger: https://github.com/faye/faye-websocket-ruby#running-the-app-with-passenger
We even have a Faye demo: https://github.com/phusion/passenger-ruby-faye-websocket-demo

**Comment by FooBarWidget** [comment]
More generally, here is documentation on how to run EventMachine on Passenger: http://www.railstips.org/blog/archives/2011/05/04/eventmachine-and-passenger/
This trick is used by Faye.
